market:
    volatilityPerc: 0.07
    fluctuationPerc: 0.05
    reversion: 0.5
    safetyMargin: 30
    interval: 3
    balancingFactor: 14
system:
    cashUser: 30
    tradingProxy: 223
    systemUrl: "{YOURHOST}"
products:
    3:
        name: Bier
        price: 1.25
        min: 0.60
        max: 2.20
        importanceFactor: 3
        order: 1
    143:
        name: Pitcher
        price: 8.50
        min: 6.50
        max: 11.00
        importanceFactor: 0.3
        order: 2
    170:
        name: Paardenkut
        price: 10
        min: 7.00
        max: 15.00
        importanceFactor: 1

    148:
        name: Amstel Radler
        price: 1.50
        min: 0.90
        max: 3.00
        importanceFactor: 1
        order: 6
    16:
        name: Flugel
        price: 1.00
        min: 0.50
        max: 2.50
        importanceFactor: 2
        order: 5
    9:
        name: Fris
        price: 1.00
        min: 0.20
        max: 4.00
        importanceFactor: 1
        order: 12
    27:
        name: 'Fristi/Chocomel'
        price: 1.50
        min: 1.00
        max: 3.50
        importanceFactor: 1
        order: 11
    22:
        name: Witte Wijn
        price: 1.50
        min: 1
        max: 3
        importanceFactor: 1
        order: 9
    164:
        name: Lustrumbier
        price: 2.00
        min: 1
        max: 3.50
        importanceFactor: 2
        order: 3
    99:
        name: Malt Bier
        price: 1.50
        min: 0.80
        max: 3
        importanceFactor: 1
        order: 10
    208:
        name: H41
        price: 2.50
        min: 1.00
        max: 4.50
        importanceFactor: 2
        order: 4
    32:
        name: Bitterballen
        price: 3.50
        min: 1.50
        max: 8.00
        importanceFactor: 0.5
        order: 13
    56:
        name: Duikbootje
        price: 2.00
        min: 0.80
        max: 3.00
        importanceFactor: 1
        order: 7
    169:
        name: Escalatieminuut
        price: 40.00
        min: 25.00
        max: 100
        importanceFactor: 0.01
        order: 14
movies:
    'bkbGqwZgWzs':
        desc: 'Bier Goedkoper'
        productId: 3
        price: 0.60
    'd2W-57qUD3g':
        desc: 'Bier duurder'
        productId: 3
        price: 1.90
    'NHjA7vfEGN0':
        desc: 'Fluger Goedkoper'
        productId: 16
        price: 0.50
    'BNbpt6uT9Zo':
        desc: 'Flugel Omhoog'
        productId: 16
        price: 2.00
    'OOBxvXVVTas':
        desc: 'Speciaalbier duurder'
        productId: 164
        price: 3.00
security:
    appSecret: YOURAPPSECRETHERE
